# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version = "2.127.2"

# skip creating README.md
skip_docs

default_platform(:android)

platform :android do

  lane :build_and_run_unit_tests_debug do
    gradle(
      task: 'clean assembleDebug testDebugUnitTest'
    )
  end

end
